#define SIGDEF_END NULL
#define SIGPAR_END NULL
#define NOARR NULL
#define DUMMY7 NULL
typedef enum WIDGETP
{
  NONO      = 0,
  YESYES    = 1 << 0,
  OOBJECT   = 1 << 1,
  JUSTFUN   = 1 << 2,
} WIDGETP;

#define __PAR_TO_VALUE(PAR_TYP,PAR_IS_GTK_WIDGET,PAR_FORMATFU,PAR_FORMAT,PAR_ARG7,ARG,VALUE) \
        /* ARG ist immer ein String, kommt von der bash */ \
        PAR_TYP VALUE; \
        if(PAR_IS_GTK_WIDGET==YESYES) { \
            GtkWidget *widget = GTK_WIDGET(gtk_builder_get_object(builder, ARG)); \
            VALUE = PAR_FORMATFU(widget); \
        } else if(PAR_IS_GTK_WIDGET==OOBJECT) { \
            void* p=atop(ARG); \
            VALUE = PAR_FORMATFU(p); \
        } else { \
            VALUE = PAR_FORMATFU(ARG); \
            /* if(DEBUG) fprintf(stderr,"    !!!! __PAR_TO_VALUE: \"%s\" => "PAR_FORMAT"\n",ARG,VALUE); */ \
        }
#define __RETOUT(RET_FORMAT) \
        if(DEBUG) fprintf(stderr,RET_FORMAT" (%s)\n",result,__func__); \
        fprintf(pargs->fpout, RET_FORMAT"\n", result); \
        fflush(pargs->fpout); 
#define __RETOUT_AND_FREE(RET_FORMAT,RET_FREEFU) \
        __RETOUT(RET_FORMAT) \
        if(RET_FREEFU) { RET_FREEFU(result); }
#define __ARR_OUT_AND_FREE(arr,RET_FORMAT,RET_TYP,RET_FREEFU) \
        RET_TYP run=arr; \
        while (*run != NULL) { \
            if(DEBUG) fprintf(stderr,RET_FORMAT" ",*run); \
            fprintf(pargs->fpout, RET_FORMAT" ", *run); \
            run++; \
        } \
        if(DEBUG) fprintf(stderr," (%s)\n",__func__); \
        fprintf(pargs->fpout, "\n"); \
        fflush(pargs->fpout); \
        if(RET_FREEFU) { RET_FREEFU(arr); } \
//
//
#define BODY1000000(RET_TYP,RET) \
    typedef RET_TYP(* gtksig_##RET)(); \
    void wrapper_##RET(GtkBuilder* builder,char* COMMAND, char*, char*, char*, char*, char*, char*) { \
        if(DEBUG) fprintf(stderr,"GTKCALL 1-0-0-0-0-0-0 %2$s() => ",__func__,COMMAND); \
        void* gtk_vu=table_get_gtk_fu(COMMAND); \
        RET_TYP result = ((gtksig_##RET)gtk_vu)(); 
#define SIGFU_DEF_RET( \
    RET, RET_TYP, RET_FORMATFU, RET_FORMAT, RET_IS_GTK_WIDGET, RET_ARG6, RET_ARG7, RET_END, \
  PARS_END ) \
    /* GtkTextDirection gtk_widget_get_default_direction() */ \
    /* SIGFU_DEF_RET(GtkTextDirection,GtkTextDirection,atoi,"%i",FALSE)*/ \
    BODY1000000(RET_TYP,RET) \
    __RETOUT(RET_FORMAT) \
    }
#define SIGFU_DEF_RETFREE( \
    RET, RET_TYP, RET_FORMATFU, RET_FORMAT, RET_IS_GTK_WIDGET, RET_FREEFU, RET_ARG7, RET_END, \
  PARS_END ) \
    BODY1000000(RET_TYP,RET) \
    __RETOUT_AND_FREE(RET_FORMAT,RET_FREEFU) \
    }
#define SIGFU_DEF_RETARR( \
    RET, RET_TYP, RET_FORMATFU, RET_FORMAT, RET_IS_GTK_WIDGET, RET_FREEFU, RET_ARG7, RET_END, \
  PARS_END ) \
    BODY1000000(RET_TYP,RET) \
    __ARR_OUT_AND_FREE(result,RET_FORMAT,RET_TYP,RET_FREEFU) \
    }
#define SIGFU_CON_RET(COMMAND, RET) /*1-0-0-0-0-0-0*/ \
    /* SIGFU_CON_RET(gtk_widget_get_default_direction, GtkTextDirection) */ \
    table_add(#COMMAND,wrapper_##RET,COMMAND);
//
//
#define BODY1100000(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7) \
    typedef RET_TYP(* gtksig_##RET##_##PAR1)(PAR1_TYP); \
    void wrapper_##RET##_##PAR1(GtkBuilder* builder,char* COMMAND, char* arg1, char*, char*, char*, char*, char*) { \
        if(DEBUG) fprintf(stderr,"GTKCALL 1-1-0-0-0-0-0 %2$s(%3$s) => ",__func__,COMMAND,arg1); \
        void* gtk_vu=table_get_gtk_fu(COMMAND); \
        __PAR_TO_VALUE(PAR1_TYP,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,arg1,value1) \
        RET_TYP result = ((gtksig_##RET##_##PAR1)gtk_vu)(value1); 
#define SIGFU_DEF_RET_PAR1( \
    RET,  RET_TYP,  RET_FORMATFU,  RET_FORMAT,  RET_IS_GTK_WIDGET, RET_ARG6, RET_ARG7, RET_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    /* gboolean gtk_window_is_fullscreen (GtkWindow* window) */ \
    /* SIGFU_DEF_RET_PAR1(gboolean,gboolean,atoi,"%i",FALSE, */ \
    /*                    GtkWindowP,GtkWindow*,GTK_WINDOW,"%p",TRUE) */ \
    BODY1100000(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7) \
    __RETOUT(RET_FORMAT) \
    }
#define SIGFU_DEF_RETFREE_PAR1( \
    RET,  RET_TYP,  RET_FORMATFU,  RET_FORMAT,  RET_IS_GTK_WIDGET, RET_FREEFU, RET_ARG7, RET_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    BODY1100000(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7) \
    __RET_OUT_AND_FREE(RET_FORMAT,RET_FREEFU) \
    }
#define SIGFU_DEF_RETARR_PAR1( \
    RET,  RET_TYP,  RET_FORMATFU,  RET_FORMAT,  RET_IS_GTK_WIDGET, RET_FREEFU, RET_ARG7, RET_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    /* e.g. char** gtk_widget_get_css_classes (GtkWidget* widget)*/ \
    /* SIGFU_DEF_ARR_PAR1(charPP,const char**,atoa,"%s",FALSE, */ \
    /*                    GtkWidgetP,GtkWidget*,GTK_WIDGET,"%p",TRUE) */ \
    BODY1100000(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7) \
    __ARR_OUT_AND_FREE(result,RET_FORMAT,RET_TYP,RET_FREEFU) \
    }
#define SIGFU_CON_RET_PAR1(COMMAND,RET,PAR1) /*1-1-0-0-0-0-0*/ \
    /* SIGFU_CON_RET_PAR1(gtk_window_is_fullscreen, gboolean, GtkWindowP) */ \
    table_add(#COMMAND,wrapper_##RET##_##PAR1,COMMAND);
//
//
#define BODY1110000(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,PAR2_TYP,PAR2,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7) \
    typedef RET_TYP(* gtksig_##RET##_##PAR1##_##PAR2)(PAR1_TYP,PAR2_TYP); \
    void wrapper_##RET##_##PAR1##_##PAR2(GtkBuilder* builder,char* COMMAND, char* arg1, char* arg2, char*, char*, char*, char*) { \
        if(DEBUG) fprintf(stderr,"GTKCALL 1-1-1-0-0-0-0 %2$s(%3$s, %4$s) => ",__func__,COMMAND,arg1,arg2); \
        void* gtk_vu=table_get_gtk_fu(COMMAND); \
        __PAR_TO_VALUE(PAR1_TYP,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,arg1,value1) \
        __PAR_TO_VALUE(PAR2_TYP,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,arg2,value2) \
        RET_TYP result = ((gtksig_##RET##_##PAR1##_##PAR2)gtk_vu)(value1, value2); 
#define SIGFU_DEF_RET_PAR2_PAR1( \
    RET,  RET_TYP,  RET_FORMATFU,  RET_FORMAT,  RET_IS_GTK_WIDGET, RET_ARG6, RET_ARG7, RET_END, \
    PAR2, PAR2_TYP, PAR2_FORMATFU, PAR2_FORMAT, PAR2_IS_GTK_WIDGET, PAR2_ARG6, PAR2_ARG7, PAR2_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    /* gboolean gtk_widget_child_focus (GtkWidget* widget, GtkDirectionType direction) */ \
    /* SIGFU_DEF_RET_PAR2_PAR1(gboolean,gboolean,atoi,"%i",FALSE, */ \
    /*                           GtkDirectionType,GtkDirectionType,atoi,"%i",FALSE, */ \
    /*                           GtkWidgetP,GtkWidget*,GTK_WIDGET,"%p",TRUE) */ \
    BODY1110000(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,PAR2_TYP,PAR2,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7) \
    __RETOUT(RET_FORMAT) \
    }
#define SIGFU_DEF_RETFREE_PAR2_PAR1( \
    RET,  RET_TYP,  RET_FORMATFU,  RET_FORMAT,  RET_IS_GTK_WIDGET, RET_FREEFU, RET_ARG7, RET_END, \
    PAR2, PAR2_TYP, PAR2_FORMATFU, PAR2_FORMAT, PAR2_IS_GTK_WIDGET, PAR2_ARG6, PAR2_ARG7, PAR2_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    BODY1110000(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,PAR2_TYP,PAR2,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7) \
    __RET_OUT_AND_FREE(RET_FORMAT,RET_FREEFU) \
    }
#define SIGFU_DEF_RETARR_PAR2_PAR1( \
    RET,  RET_TYP,  RET_FORMATFU,  RET_FORMAT,  RET_IS_GTK_WIDGET, RET_FREEFU, RET_ARG7, RET_END, \
    PAR2, PAR2_TYP, PAR2_FORMATFU, PAR2_FORMAT, PAR2_IS_GTK_WIDGET, PAR2_ARG6, PAR2_ARG7, PAR2_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    BODY1110000(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,PAR2_TYP,PAR2,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7) \
    __ARR_OUT_AND_FREE(result,RET_FORMAT,RET_TYP,RET_FREEFU) \
    }
#define SIGFU_CON_RET_PAR1_PAR2(COMMAND,RET,PAR1,PAR2) /*1-1-1-0-0-0-0*/ \
    /* SIGFU_CON_RET_PAR1_PAR2(gtk_widget_child_focus,gboolean,GtkWidgetP,GtkDirectionType) */ \
    table_add(#COMMAND,wrapper_##RET##_##PAR1##_##PAR2,COMMAND);
//
//
#define BODY1111000(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,PAR2_TYP,PAR2,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,PAR3_TYP,PAR3,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7) \
    typedef RET_TYP(* gtksig_##RET##_##PAR1##_##PAR2##_##PAR3)(PAR1_TYP,PAR2_TYP,PAR3_TYP); \
    void wrapper_##RET##_##PAR1##_##PAR2##_##PAR3(GtkBuilder* builder,char* COMMAND, char* arg1, char* arg2, char* arg3, char*, char*, char*) { \
        if(DEBUG) fprintf(stderr,"GTKCALL 1-1-1-1-0-0-0 %2$s(%3$s, %4$s, %5$s) => ",__func__,COMMAND,arg1,arg2,arg3); \
        void* gtk_vu=table_get_gtk_fu(COMMAND); \
        __PAR_TO_VALUE(PAR1_TYP,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,arg1,value1) \
        __PAR_TO_VALUE(PAR2_TYP,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,arg2,value2) \
        __PAR_TO_VALUE(PAR3_TYP,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7,arg3,value3) \
        RET_TYP result = ((gtksig_##RET##_##PAR1##_##PAR2##_##PAR3)gtk_vu)(value1, value2, value3); 
#define SIGFU_DEF_RET_PAR2_PAR3_PAR1( \
    RET,  RET_TYP,  RET_FORMATFU,  RET_FORMAT,  RET_IS_GTK_WIDGET, RET_ARG6, RET_ARG7, RET_END, \
    PAR2, PAR2_TYP, PAR2_FORMATFU, PAR2_FORMAT, PAR2_IS_GTK_WIDGET, PAR2_ARG6, PAR2_ARG7, PAR2_END, \
    PAR3, PAR3_TYP, PAR3_FORMATFU, PAR3_FORMAT, PAR3_IS_GTK_WIDGET, PAR3_ARG6, PAR3_ARG7, PAR3_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    BODY1111000(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,PAR2_TYP,PAR2,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,PAR3_TYP,PAR3,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7) \
    __RETOUT(RET_FORMAT) \
    }
#define SIGFU_DEF_RETFREE_PAR2_PAR3_PAR1( \
    RET,  RET_TYP,  RET_FORMATFU,  RET_FORMAT,  RET_IS_GTK_WIDGET, RET_FREEFU, RET_ARG7, RET_END, \
    PAR2, PAR2_TYP, PAR2_FORMATFU, PAR2_FORMAT, PAR2_IS_GTK_WIDGET, PAR2_ARG6, PAR2_ARG7, PAR2_END, \
    PAR3, PAR3_TYP, PAR3_FORMATFU, PAR3_FORMAT, PAR3_IS_GTK_WIDGET, PAR3_ARG6, PAR3_ARG7, PAR3_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    BODY1111000(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,PAR2_TYP,PAR2,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,PAR3_TYP,PAR3,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7) \
    __RET_OUT_AND_FREE(RET_FORMAT,RET_FREEFU) \
    }
#define SIGFU_DEF_RETARR_PAR2_PAR3_PAR1( \
    RET,  RET_TYP,  RET_FORMATFU,  RET_FORMAT,  RET_IS_GTK_WIDGET, RET_FREEFU, RET_ARG7, RET_END, \
    PAR2, PAR2_TYP, PAR2_FORMATFU, PAR2_FORMAT, PAR2_IS_GTK_WIDGET, PAR2_ARG6, PAR2_ARG7, PAR2_END, \
    PAR3, PAR3_TYP, PAR3_FORMATFU, PAR3_FORMAT, PAR3_IS_GTK_WIDGET, PAR3_ARG6, PAR3_ARG7, PAR3_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    BODY1111000(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,PAR2_TYP,PAR2,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,PAR3_TYP,PAR3,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7) \
    __ARR_OUT_AND_FREE(result,RET_FORMAT,RET_TYP,RET_FREEFU) \
    }
#define SIGFU_CON_RET_PAR1_PAR2_PAR3(COMMAND,RET,PAR1,PAR2,PAR3) /*1-1-1-1-0-0-0*/ \
    table_add(#COMMAND,wrapper_##RET##_##PAR1##_##PAR2##_##PAR3,COMMAND);
//
//
#define BODY1111100(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,PAR2_TYP,PAR2,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,PAR3_TYP,PAR3,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7,PAR4_TYP,PAR4,PAR4_IS_GTK_WIDGET,PAR4_FORMATFU,PAR4_FORMAT,PAR4_ARG7) \
    typedef RET_TYP(* gtksig_##RET##_##PAR1##_##PAR2##_##PAR3##_##PAR4)(PAR1_TYP,PAR2_TYP,PAR3_TYP,PAR4_TYP); \
    void wrapper_##RET##_##PAR1##_##PAR2##_##PAR3##_##PAR4(GtkBuilder* builder,char* COMMAND, char* arg1, char* arg2, char* arg3, char* arg4, char*, char*) { \
        if(DEBUG) fprintf(stderr,"GTKCALL 1-1-1-1-1-0-0 %2$s(%3$s, %4$s, %5$s, %6$s) => ",__func__,COMMAND,arg1,arg2,arg3,arg4); \
        void* gtk_vu=table_get_gtk_fu(COMMAND); \
        __PAR_TO_VALUE(PAR1_TYP,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,arg1,value1) \
        __PAR_TO_VALUE(PAR2_TYP,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,arg2,value2) \
        __PAR_TO_VALUE(PAR3_TYP,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7,arg3,value3) \
        __PAR_TO_VALUE(PAR4_TYP,PAR4_IS_GTK_WIDGET,PAR4_FORMATFU,PAR4_FORMAT,PAR4_ARG7,arg4,value4) \
        RET_TYP result = ((gtksig_##RET##_##PAR1##_##PAR2##_##PAR3##_##PAR4)gtk_vu)(value1, value2, value3, value4);
#define SIGFU_DEF_RET_PAR2_PAR3_PAR4_PAR1( \
    RET,  RET_TYP,  RET_FORMATFU,  RET_FORMAT,  RET_IS_GTK_WIDGET, RET_ARG6, RET_ARG7, RET_END, \
    PAR2, PAR2_TYP, PAR2_FORMATFU, PAR2_FORMAT, PAR2_IS_GTK_WIDGET, PAR2_ARG6, PAR2_ARG7, PAR2_END, \
    PAR3, PAR3_TYP, PAR3_FORMATFU, PAR3_FORMAT, PAR3_IS_GTK_WIDGET, PAR3_ARG6, PAR3_ARG7, PAR3_END, \
    PAR4, PAR4_TYP, PAR4_FORMATFU, PAR4_FORMAT, PAR4_IS_GTK_WIDGET, PAR4_ARG6, PAR4_ARG7, PAR4_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    BODY1111100(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,PAR2_TYP,PAR2,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,PAR3_TYP,PAR3,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7,PAR4_TYP,PAR4,PAR4_IS_GTK_WIDGET,PAR4_FORMATFU,PAR4_FORMAT,PAR4_ARG7) \
    __RETOUT(RET_FORMAT) \
    }
#define SIGFU_DEF_RETFREE_PAR2_PAR3_PAR4_PAR1( \
    RET,  RET_TYP,  RET_FORMATFU,  RET_FORMAT,  RET_IS_GTK_WIDGET, RET_FREEFU, RET_ARG7, RET_END, \
    PAR2, PAR2_TYP, PAR2_FORMATFU, PAR2_FORMAT, PAR2_IS_GTK_WIDGET, PAR2_ARG6, PAR2_ARG7, PAR2_END, \
    PAR3, PAR3_TYP, PAR3_FORMATFU, PAR3_FORMAT, PAR3_IS_GTK_WIDGET, PAR3_ARG6, PAR3_ARG7, PAR3_END, \
    PAR4, PAR4_TYP, PAR4_FORMATFU, PAR4_FORMAT, PAR4_IS_GTK_WIDGET, PAR4_ARG6, PAR4_ARG7, PAR4_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    BODY1111100(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,PAR2_TYP,PAR2,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,PAR3_TYP,PAR3,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7,PAR4_TYP,PAR4,PAR4_IS_GTK_WIDGET,PAR4_FORMATFU,PAR4_FORMAT,PAR4_ARG7) \
    __RETOUT_AND_FREE(RET_FORMAT,RET_FREEFU) \
    }
#define SIGFU_DEF_RETARR_PAR2_PAR3_PAR4_PAR1( \
    RET,  RET_TYP,  RET_FORMATFU,  RET_FORMAT,  RET_IS_GTK_WIDGET, RET_FREEFU, RET_ARG7, RET_END, \
    PAR2, PAR2_TYP, PAR2_FORMATFU, PAR2_FORMAT, PAR2_IS_GTK_WIDGET, PAR2_ARG6, PAR2_ARG7, PAR2_END, \
    PAR3, PAR3_TYP, PAR3_FORMATFU, PAR3_FORMAT, PAR3_IS_GTK_WIDGET, PAR3_ARG6, PAR3_ARG7, PAR3_END, \
    PAR4, PAR4_TYP, PAR4_FORMATFU, PAR4_FORMAT, PAR4_IS_GTK_WIDGET, PAR4_ARG6, PAR4_ARG7, PAR4_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    BODY1111100(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,PAR2_TYP,PAR2,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,PAR3_TYP,PAR3,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7,PAR4_TYP,PAR4,PAR4_IS_GTK_WIDGET,PAR4_FORMATFU,PAR4_FORMAT,PAR4_ARG7) \
    __ARR_OUT_AND_FREE(result,RET_FORMAT,RET_TYP,RET_FREEFU) \
    }
#define SIGFU_CON_RET_PAR1_PAR2_PAR3_PAR4(COMMAND,RET,PAR1,PAR2,PAR3,PAR4) /*1-1-1-1-1-0-0*/ \
    table_add(#COMMAND,wrapper_##RET##_##PAR1##_##PAR2##_##PAR3##_##PAR4,COMMAND);
//
//
#define BODY1111110(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,PAR2_TYP,PAR2,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,PAR3_TYP,PAR3,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7,PAR4_TYP,PAR4,PAR4_IS_GTK_WIDGET,PAR4_FORMATFU,PAR4_FORMAT,PAR4_ARG7,PAR5_TYP,PAR5,PAR5_IS_GTK_WIDGET,PAR5_FORMATFU,PAR5_FORMAT,PAR5_ARG7) \
    typedef RET_TYP(* gtksig_##RET##_##PAR1##_##PAR2##_##PAR3##_##PAR4##_##PAR5)(PAR1_TYP,PAR2_TYP,PAR3_TYP,PAR4_TYP,PAR5_TYP); \
    void wrapper_##RET##_##PAR1##_##PAR2##_##PAR3##_##PAR4##_##PAR5(GtkBuilder* builder,char* COMMAND, char* arg1, char* arg2, char* arg3, char* arg4, char* arg5, char*) { \
        if(DEBUG) fprintf(stderr,"GTKCALL 1-1-1-1-1-1-0 %2$s(%3$s, %4$s, %5$s, %6$s, %7$s) => ",__func__,COMMAND,arg1,arg2,arg3,arg4,arg5); \
        void* gtk_vu=table_get_gtk_fu(COMMAND); \
        __PAR_TO_VALUE(PAR1_TYP,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,arg1,value1) \
        __PAR_TO_VALUE(PAR2_TYP,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,arg2,value2) \
        __PAR_TO_VALUE(PAR3_TYP,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7,arg3,value3) \
        __PAR_TO_VALUE(PAR4_TYP,PAR4_IS_GTK_WIDGET,PAR4_FORMATFU,PAR4_FORMAT,PAR4_ARG7,arg4,value4) \
        __PAR_TO_VALUE(PAR5_TYP,PAR5_IS_GTK_WIDGET,PAR5_FORMATFU,PAR5_FORMAT,PAR5_ARG7,arg5,value5) \
        RET_TYP result = ((gtksig_##RET##_##PAR1##_##PAR2##_##PAR3##_##PAR4##_##PAR5)gtk_vu)(value1, value2, value3, value4, value5);
#define SIGFU_DEF_RET_PAR2_PAR3_PAR4_PAR5_PAR1( \
    RET,  RET_TYP,  RET_FORMATFU,  RET_FORMAT,  RET_IS_GTK_WIDGET, RET_ARG6, RET_ARG7, RET_END, \
    PAR2, PAR2_TYP, PAR2_FORMATFU, PAR2_FORMAT, PAR2_IS_GTK_WIDGET, PAR2_ARG6, PAR2_ARG7, PAR2_END, \
    PAR3, PAR3_TYP, PAR3_FORMATFU, PAR3_FORMAT, PAR3_IS_GTK_WIDGET, PAR3_ARG6, PAR3_ARG7, PAR3_END, \
    PAR4, PAR4_TYP, PAR4_FORMATFU, PAR4_FORMAT, PAR4_IS_GTK_WIDGET, PAR4_ARG6, PAR4_ARG7, PAR4_END, \
    PAR5, PAR5_TYP, PAR5_FORMATFU, PAR5_FORMAT, PAR5_IS_GTK_WIDGET, PAR5_ARG6, PAR5_ARG7, PAR5_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    BODY1111110(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,PAR2_TYP,PAR2,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,PAR3_TYP,PAR3,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7,PAR4_TYP,PAR4,PAR4_IS_GTK_WIDGET,PAR4_FORMATFU,PAR4_FORMAT,PAR4_ARG7,PAR5_TYP,PAR5,PAR5_IS_GTK_WIDGET,PAR5_FORMATFU,PAR5_FORMAT,PAR5_ARG7) \
    __RETOUT(RET_FORMAT) \
    }
#define SIGFU_DEF_RETFREE_PAR2_PAR3_PAR4_PAR5_PAR1( \
    RET,  RET_TYP,  RET_FORMATFU,  RET_FORMAT,  RET_IS_GTK_WIDGET, RET_FREEFU, RET_ARG7, RET_END, \
    PAR2, PAR2_TYP, PAR2_FORMATFU, PAR2_FORMAT, PAR2_IS_GTK_WIDGET, PAR2_ARG6, PAR2_ARG7, PAR2_END, \
    PAR3, PAR3_TYP, PAR3_FORMATFU, PAR3_FORMAT, PAR3_IS_GTK_WIDGET, PAR3_ARG6, PAR3_ARG7, PAR3_END, \
    PAR4, PAR4_TYP, PAR4_FORMATFU, PAR4_FORMAT, PAR4_IS_GTK_WIDGET, PAR4_ARG6, PAR4_ARG7, PAR4_END, \
    PAR5, PAR5_TYP, PAR5_FORMATFU, PAR5_FORMAT, PAR5_IS_GTK_WIDGET, PAR5_ARG6, PAR5_ARG7, PAR5_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    BODY1111110(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,PAR2_TYP,PAR2,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,PAR3_TYP,PAR3,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7,PAR4_TYP,PAR4,PAR4_IS_GTK_WIDGET,PAR4_FORMATFU,PAR4_FORMAT,PAR4_ARG7,PAR5_TYP,PAR5,PAR5_IS_GTK_WIDGET,PAR5_FORMATFU,PAR5_FORMAT,PAR5_ARG7) \
    __RET_OUT_AND_FREE(RET_FORMAT,RET_FREEFU) \
    }
#define SIGFU_DEF_RETARR_PAR2_PAR3_PAR4_PAR5_PAR1( \
    RET,  RET_TYP,  RET_FORMATFU,  RET_FORMAT,  RET_IS_GTK_WIDGET, RET_FREEFU, RET_ARG7, RET_END, \
    PAR2, PAR2_TYP, PAR2_FORMATFU, PAR2_FORMAT, PAR2_IS_GTK_WIDGET, PAR2_ARG6, PAR2_ARG7, PAR2_END, \
    PAR3, PAR3_TYP, PAR3_FORMATFU, PAR3_FORMAT, PAR3_IS_GTK_WIDGET, PAR3_ARG6, PAR3_ARG7, PAR3_END, \
    PAR4, PAR4_TYP, PAR4_FORMATFU, PAR4_FORMAT, PAR4_IS_GTK_WIDGET, PAR4_ARG6, PAR4_ARG7, PAR4_END, \
    PAR5, PAR5_TYP, PAR5_FORMATFU, PAR5_FORMAT, PAR5_IS_GTK_WIDGET, PAR5_ARG6, PAR5_ARG7, PAR5_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    BODY1111110(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,PAR2_TYP,PAR2,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,PAR3_TYP,PAR3,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7,PAR4_TYP,PAR4,PAR4_IS_GTK_WIDGET,PAR4_FORMATFU,PAR4_FORMAT,PAR4_ARG7,PAR5_TYP,PAR5,PAR5_IS_GTK_WIDGET,PAR5_FORMATFU,PAR5_FORMAT,PAR5_ARG7) \
    __ARR_OUT_AND_FREE(result,RET_FORMAT,RET_TYP,RET_FREEFU) \
    }
#define SIGFU_CON_RET_PAR1_PAR2_PAR3_PAR4_PAR5(COMMAND,RET,PAR1,PAR2,PAR3,PAR4,PAR5) /*1-1-1-1-1-1-0*/ \
    table_add(#COMMAND,wrapper_##RET##_##PAR1##_##PAR2##_##PAR3##_##PAR4##_##PAR5,COMMAND);
//
//
#define BODY1111111(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,PAR2_TYP,PAR2,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,PAR3_TYP,PAR3,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7,PAR4_TYP,PAR4,PAR4_IS_GTK_WIDGET,PAR4_FORMATFU,PAR4_FORMAT,PAR4_ARG7,PAR5_TYP,PAR5,PAR5_IS_GTK_WIDGET,PAR5_FORMATFU,PAR5_FORMAT,PAR5_ARG7,PAR6_TYP,PAR6,PAR6_IS_GTK_WIDGET,PAR6_FORMATFU,PAR6_FORMAT,PAR6_ARG7) \
    typedef RET_TYP(* gtksig_##RET##_##PAR1##_##PAR2##_##PAR3##_##PAR4##_##PAR5##_##PAR6)(PAR1_TYP,PAR2_TYP,PAR3_TYP,PAR4_TYP,PAR5_TYP,PAR6_TYP); \
    void wrapper_##RET##_##PAR1##_##PAR2##_##PAR3##_##PAR4##_##PAR5##_##PAR6(GtkBuilder* builder,char* COMMAND, char* arg1, char* arg2, char* arg3, char* arg4, char* arg5, char* arg6) { \
        if(DEBUG) fprintf(stderr,"GTKCALL 1-1-1-1-1-1-1 %2$s(%3$s, %4$s, %5$s, %6$s, %7$s, %8$s) => ",__func__,COMMAND,arg1,arg2,arg3,arg4,arg5,arg6); \
        void* gtk_vu=table_get_gtk_fu(COMMAND); \
        __PAR_TO_VALUE(PAR1_TYP,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,arg1,value1) \
        __PAR_TO_VALUE(PAR2_TYP,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,arg2,value2) \
        __PAR_TO_VALUE(PAR3_TYP,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7,arg3,value3) \
        __PAR_TO_VALUE(PAR4_TYP,PAR4_IS_GTK_WIDGET,PAR4_FORMATFU,PAR4_FORMAT,PAR4_ARG7,arg4,value4) \
        __PAR_TO_VALUE(PAR5_TYP,PAR5_IS_GTK_WIDGET,PAR5_FORMATFU,PAR5_FORMAT,PAR5_ARG7,arg5,value5) \
        __PAR_TO_VALUE(PAR6_TYP,PAR6_IS_GTK_WIDGET,PAR6_FORMATFU,PAR6_FORMAT,PAR6_ARG7,arg6,value6) \
        RET_TYP result = ((gtksig_##RET##_##PAR1##_##PAR2##_##PAR3##_##PAR4##_##PAR5##_##PAR6)gtk_vu)(value1, value2, value3, value4, value5, value6);
#define SIGFU_DEF_RET_PAR2_PAR3_PAR4_PAR5_PAR6_PAR1( \
    RET,  RET_TYP,  RET_FORMATFU,  RET_FORMAT,  RET_IS_GTK_WIDGET, RET_ARG6, RET_ARG7, RET_END, \
    PAR2, PAR2_TYP, PAR2_FORMATFU, PAR2_FORMAT, PAR2_IS_GTK_WIDGET, PAR2_ARG6, PAR2_ARG7, PAR2_END, \
    PAR3, PAR3_TYP, PAR3_FORMATFU, PAR3_FORMAT, PAR3_IS_GTK_WIDGET, PAR3_ARG6, PAR3_ARG7, PAR3_END, \
    PAR4, PAR4_TYP, PAR4_FORMATFU, PAR4_FORMAT, PAR4_IS_GTK_WIDGET, PAR4_ARG6, PAR4_ARG7, PAR4_END, \
    PAR5, PAR5_TYP, PAR5_FORMATFU, PAR5_FORMAT, PAR5_IS_GTK_WIDGET, PAR5_ARG6, PAR5_ARG7, PAR5_END, \
    PAR6, PAR6_TYP, PAR6_FORMATFU, PAR6_FORMAT, PAR6_IS_GTK_WIDGET, PAR6_ARG6, PAR6_ARG7, PAR6_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    BODY1111111(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,PAR2_TYP,PAR2,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,PAR3_TYP,PAR3,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7,PAR4_TYP,PAR4,PAR4_IS_GTK_WIDGET,PAR4_FORMATFU,PAR4_FORMAT,PAR4_ARG7,PAR5_TYP,PAR5,PAR5_IS_GTK_WIDGET,PAR5_FORMATFU,PAR5_FORMAT,PAR5_ARG7,PAR6_TYP,PAR6,PAR6_IS_GTK_WIDGET,PAR6_FORMATFU,PAR6_FORMAT,PAR6_ARG7) \
    __RETOUT(RET_FORMAT) \
    }
#define SIGFU_DEF_RETFREE_PAR2_PAR3_PAR4_PAR5_PAR6_PAR1( \
    RET,  RET_TYP,  RET_FORMATFU,  RET_FORMAT,  RET_IS_GTK_WIDGET, RET_FREEFU, RET_ARG7, RET_END, \
    PAR2, PAR2_TYP, PAR2_FORMATFU, PAR2_FORMAT, PAR2_IS_GTK_WIDGET, PAR2_ARG6, PAR2_ARG7, PAR2_END, \
    PAR3, PAR3_TYP, PAR3_FORMATFU, PAR3_FORMAT, PAR3_IS_GTK_WIDGET, PAR3_ARG6, PAR3_ARG7, PAR3_END, \
    PAR4, PAR4_TYP, PAR4_FORMATFU, PAR4_FORMAT, PAR4_IS_GTK_WIDGET, PAR4_ARG6, PAR4_ARG7, PAR4_END, \
    PAR5, PAR5_TYP, PAR5_FORMATFU, PAR5_FORMAT, PAR5_IS_GTK_WIDGET, PAR5_ARG6, PAR5_ARG7, PAR5_END, \
    PAR6, PAR6_TYP, PAR6_FORMATFU, PAR6_FORMAT, PAR6_IS_GTK_WIDGET, PAR6_ARG6, PAR6_ARG7, PAR6_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    BODY1111111(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,PAR2_TYP,PAR2,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,PAR3_TYP,PAR3,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7,PAR4_TYP,PAR4,PAR4_IS_GTK_WIDGET,PAR4_FORMATFU,PAR4_FORMAT,PAR4_ARG7,PAR5_TYP,PAR5,PAR5_IS_GTK_WIDGET,PAR5_FORMATFU,PAR5_FORMAT,PAR5_ARG7,PAR6_TYP,PAR6,PAR6_IS_GTK_WIDGET,PAR6_FORMATFU,PAR6_FORMAT,PAR6_ARG7) \
    __RET_OUT_AND_FREE(RET_FORMAT,RET_FREEFU) \
    }
#define SIGFU_DEF_RETARR_PAR2_PAR3_PAR4_PAR5_PAR6_PAR1( \
    RET,  RET_TYP,  RET_FORMATFU,  RET_FORMAT,  RET_IS_GTK_WIDGET, RET_FREEFU, RET_ARG7, RET_END, \
    PAR2, PAR2_TYP, PAR2_FORMATFU, PAR2_FORMAT, PAR2_IS_GTK_WIDGET, PAR2_ARG6, PAR2_ARG7, PAR2_END, \
    PAR3, PAR3_TYP, PAR3_FORMATFU, PAR3_FORMAT, PAR3_IS_GTK_WIDGET, PAR3_ARG6, PAR3_ARG7, PAR3_END, \
    PAR4, PAR4_TYP, PAR4_FORMATFU, PAR4_FORMAT, PAR4_IS_GTK_WIDGET, PAR4_ARG6, PAR4_ARG7, PAR4_END, \
    PAR5, PAR5_TYP, PAR5_FORMATFU, PAR5_FORMAT, PAR5_IS_GTK_WIDGET, PAR5_ARG6, PAR5_ARG7, PAR5_END, \
    PAR6, PAR6_TYP, PAR6_FORMATFU, PAR6_FORMAT, PAR6_IS_GTK_WIDGET, PAR6_ARG6, PAR6_ARG7, PAR6_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    BODY1111111(RET_TYP,RET,PAR1_TYP,PAR1,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,PAR2_TYP,PAR2,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,PAR3_TYP,PAR3,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7,PAR4_TYP,PAR4,PAR4_IS_GTK_WIDGET,PAR4_FORMATFU,PAR4_FORMAT,PAR4_ARG7,PAR5_TYP,PAR5,PAR5_IS_GTK_WIDGET,PAR5_FORMATFU,PAR5_FORMAT,PAR5_ARG7,PAR6_TYP,PAR6,PAR6_IS_GTK_WIDGET,PAR6_FORMATFU,PAR6_FORMAT,PAR6_ARG7) \
    __ARR_OUT_AND_FREE(result,RET_FORMAT,RET_TYP,RET_FREEFU) \
    }
#define SIGFU_CON_RET_PAR1_PAR2_PAR3_PAR4_PAR5_PAR6(COMMAND,RET,PAR1,PAR2,PAR3,PAR4,PAR5,PAR6) /*1-1-1-1-1-1-1*/ \
    table_add(#COMMAND,wrapper_##RET##_##PAR1##_##PAR2##_##PAR3##_##PAR4##_##PAR5_##PAR6,COMMAND);
//
//
#define SIGFU_DEF_VOID_PAR1( \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    /* void gtk_window_set_auto_startup_notification(gboolean) */ \
    /* SIGFU_DEF_VOID_PAR1(gboolean,gboolean,atoi,"%i",FALSE) */ \
    /* void gtk_window_maximize(GtkWindow* window) */ \
    /* SIGFU_DEF_VOID_PAR1(GtkWindowP,GtkWindow*,GTK_WINDOW,"%p",TRUE) */ \
    typedef void(* gtksig_void_##PAR1)(PAR1_TYP); \
    void wrapper_void_##PAR1(GtkBuilder* builder,char* COMMAND, char* arg1, char*, char*, char*, char*, char*) { \
        if(DEBUG) fprintf(stderr,"GTKCALL 0-1-0-0-0-0-0 %2$s(%3$s) (%1$s)\n",__func__,COMMAND,arg1); \
        void* gtk_vu=table_get_gtk_fu(COMMAND); \
        __PAR_TO_VALUE(PAR1_TYP,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,arg1,value1) \
        ((gtksig_void_##PAR1)gtk_vu)(value1); \
    }
#define SIGFU_CON_VOID_PAR1(COMMAND,PAR1) /*0-1-0-0-0-0-0*/ \
    /* SIGFU_CON_VOID_PAR1(gtk_window_set_auto_startup_notification, gboolean) */ \
    /* SIGFU_CON_VOID_PAR1(gtk_window_maximize, GtkWindowP) */ \
    table_add(#COMMAND,wrapper_void_##PAR1,COMMAND);
//
//
#define SIGFU_DEF_VOID_PAR2_PAR1( \
    PAR2, PAR2_TYP, PAR2_FORMATFU, PAR2_FORMAT, PAR2_IS_GTK_WIDGET, PAR2_ARG6, PAR2_ARG7, PAR2_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    /* SIGFU_DEF_VOID_PAR2_PAR1(constcharP,const char*,atoa,"%s",FALSE, */ \
    /* GtkWindowP,GtkWindow*,GTK_WINDOW,"%p",TRUE) */ \
    typedef void(* gtksig_void_##PAR1##_##PAR2)(PAR1_TYP,PAR2_TYP); \
    void wrapper_void_##PAR1##_##PAR2(GtkBuilder* builder,char* COMMAND, char* arg1, char* arg2, char*, char*, char*, char*) { \
        if(DEBUG) fprintf(stderr,"GTKCALL 0-1-1-0-0-0-0 %2$s(%3$s, %4$s) (%1$s)\n",__func__,COMMAND,arg1,arg2); \
        void* gtk_vu=table_get_gtk_fu(COMMAND); \
        __PAR_TO_VALUE(PAR1_TYP,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,arg1,value1) \
        __PAR_TO_VALUE(PAR2_TYP,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,arg2,value2) \
        ((gtksig_void_##PAR1##_##PAR2)gtk_vu)(value1,value2); \
    }
#define SIGFU_CON_VOID_PAR1_PAR2(COMMAND,PAR1,PAR2) /*0-1-1-0-0-0-0*/ \
    /* SIGFU_CON_VOID_gtkclassP_PAR2(gtk_window_set_title, GtkWindowP, constcharP) */ \
    table_add(#COMMAND,wrapper_void_##PAR1##_##PAR2,COMMAND);
//
//
#define SIGFU_DEF_VOID_PAR2_PAR3_PAR1( \
    PAR2, PAR2_TYP, PAR2_FORMATFU, PAR2_FORMAT, PAR2_IS_GTK_WIDGET, PAR2_ARG6, PAR2_ARG7, PAR2_END, \
    PAR3, PAR3_TYP, PAR3_FORMATFU, PAR3_FORMAT, PAR3_IS_GTK_WIDGET, PAR3_ARG6, PAR3_ARG7, PAR3_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    typedef void(* gtksig_void_##PAR1##_##PAR2##_##PAR3)(PAR1_TYP,PAR2_TYP,PAR3_TYP); \
    void wrapper_void_##PAR1##_##PAR2##_##PAR3(GtkBuilder* builder,char* COMMAND, char* arg1, char* arg2, char* arg3, char*, char*, char*) { \
        if(DEBUG) fprintf(stderr,"GTKCALL 0-1-1-1-0-0-0 %2$s(%3$s, %4$s, %5$s) (%1$s)\n",__func__,COMMAND,arg1,arg2,arg3); \
        void* gtk_vu=table_get_gtk_fu(COMMAND); \
        __PAR_TO_VALUE(PAR1_TYP,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,arg1,value1) \
        __PAR_TO_VALUE(PAR2_TYP,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,arg2,value2) \
        __PAR_TO_VALUE(PAR3_TYP,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7,arg3,value3) \
        ((gtksig_void_##PAR1##_##PAR2##_##PAR3)gtk_vu)(value1,value2,value3); \
    }
#define SIGFU_CON_VOID_PAR1_PAR2_PAR3(COMMAND,PAR1,PAR2,PAR3) /*0-1-1-1-0-0-0*/ \
    table_add(#COMMAND,wrapper_void_##PAR1##_##PAR2##_##PAR3,COMMAND);
//
//
#define SIGFU_DEF_VOID_PAR2_PAR3_PAR4_PAR1( \
    PAR2, PAR2_TYP, PAR2_FORMATFU, PAR2_FORMAT, PAR2_IS_GTK_WIDGET, PAR2_ARG6, PAR2_ARG7, PAR2_END, \
    PAR3, PAR3_TYP, PAR3_FORMATFU, PAR3_FORMAT, PAR3_IS_GTK_WIDGET, PAR3_ARG6, PAR3_ARG7, PAR3_END, \
    PAR4, PAR4_TYP, PAR4_FORMATFU, PAR4_FORMAT, PAR4_IS_GTK_WIDGET, PAR4_ARG6, PAR4_ARG7, PAR4_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    typedef void(* gtksig_void_##PAR1##_##PAR2##_##PAR3##_##PAR4)(PAR1_TYP,PAR2_TYP,PAR3_TYP,PAR4_TYP); \
    void wrapper_void_##PAR1##_##PAR2##_##PAR3##_##PAR4(GtkBuilder* builder,char* COMMAND, char* arg1, char* arg2, char* arg3, char* arg4, char*, char*) { \
        if(DEBUG) fprintf(stderr,"GTKCALL 0-1-1-1-1-0-0 %2$s(%3$s, %4$s, %5$s, %6$s) (%1$s)\n",__func__,COMMAND,arg1,arg2,arg3,arg4); \
        void* gtk_vu=table_get_gtk_fu(COMMAND); \
        __PAR_TO_VALUE(PAR1_TYP,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,arg1,value1) \
        __PAR_TO_VALUE(PAR2_TYP,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,arg2,value2) \
        __PAR_TO_VALUE(PAR3_TYP,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7,arg3,value3) \
        __PAR_TO_VALUE(PAR4_TYP,PAR4_IS_GTK_WIDGET,PAR4_FORMATFU,PAR4_FORMAT,PAR4_ARG7,arg4,value4) \
        ((gtksig_void_##PAR1##_##PAR2##_##PAR3##_##PAR4)gtk_vu)(value1,value2,value3,value4); \
    }
#define SIGFU_CON_VOID_PAR1_PAR2_PAR3_PAR4(COMMAND,PAR1,PAR2,PAR3,PAR4) /*0-1-1-1-1-0-0*/ \
    table_add(#COMMAND,wrapper_void_##PAR1##_##PAR2##_##PAR3##_##PAR4,COMMAND);
//
//
#define SIGFU_DEF_VOID_PAR2_PAR3_PAR4_PAR5_PAR1( \
    PAR2, PAR2_TYP, PAR2_FORMATFU, PAR2_FORMAT, PAR2_IS_GTK_WIDGET, PAR2_ARG6, PAR2_ARG7, PAR2_END, \
    PAR3, PAR3_TYP, PAR3_FORMATFU, PAR3_FORMAT, PAR3_IS_GTK_WIDGET, PAR3_ARG6, PAR3_ARG7, PAR3_END, \
    PAR4, PAR4_TYP, PAR4_FORMATFU, PAR4_FORMAT, PAR4_IS_GTK_WIDGET, PAR4_ARG6, PAR4_ARG7, PAR4_END, \
    PAR5, PAR5_TYP, PAR5_FORMATFU, PAR5_FORMAT, PAR5_IS_GTK_WIDGET, PAR5_ARG6, PAR5_ARG7, PAR5_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    typedef void(* gtksig_void_##PAR1##_##PAR2##_##PAR3##_##PAR4##_##PAR5)(PAR1_TYP,PAR2_TYP,PAR3_TYP,PAR4_TYP,PAR5_TYP); \
    void wrapper_void_##PAR1##_##PAR2##_##PAR3##_##PAR4##_##PAR5(GtkBuilder* builder,char* COMMAND, char* arg1, char* arg2, char* arg3, char* arg4, char* arg5, char*) { \
        if(DEBUG) fprintf(stderr,"GTKCALL 0-1-1-1-1-1-0 %2$s(%3$s, %4$s, %5$s, %6$s, %7$s) (%1$s)\n",__func__,COMMAND,arg1,arg2,arg3,arg4,arg5); \
        void* gtk_vu=table_get_gtk_fu(COMMAND); \
        __PAR_TO_VALUE(PAR1_TYP,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,arg1,value1) \
        __PAR_TO_VALUE(PAR2_TYP,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,arg2,value2) \
        __PAR_TO_VALUE(PAR3_TYP,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7,arg3,value3) \
        __PAR_TO_VALUE(PAR4_TYP,PAR4_IS_GTK_WIDGET,PAR4_FORMATFU,PAR4_FORMAT,PAR4_ARG7,arg4,value4) \
        __PAR_TO_VALUE(PAR5_TYP,PAR5_IS_GTK_WIDGET,PAR5_FORMATFU,PAR5_FORMAT,PAR5_ARG7,arg5,value5) \
        ((gtksig_void_##PAR1##_##PAR2##_##PAR3##_##PAR4##_##PAR5)gtk_vu)(value1,value2,value3,value4,value5); \
    }
#define SIGFU_CON_VOID_PAR1_PAR2_PAR3_PAR4_PAR5(COMMAND,PAR1,PAR2,PAR3,PAR4,PAR5) /*0-1-1-1-1-1-0*/ \
    table_add(#COMMAND,wrapper_void_##PAR1##_##PAR2##_##PAR3##_##PAR4##_##PAR5,COMMAND);
//
//
#define SIGFU_DEF_VOID_PAR2_PAR3_PAR4_PAR5_PAR6_PAR1( \
    PAR2, PAR2_TYP, PAR2_FORMATFU, PAR2_FORMAT, PAR2_IS_GTK_WIDGET, PAR2_ARG6, PAR2_ARG7, PAR2_END, \
    PAR3, PAR3_TYP, PAR3_FORMATFU, PAR3_FORMAT, PAR3_IS_GTK_WIDGET, PAR3_ARG6, PAR3_ARG7, PAR3_END, \
    PAR4, PAR4_TYP, PAR4_FORMATFU, PAR4_FORMAT, PAR4_IS_GTK_WIDGET, PAR4_ARG6, PAR4_ARG7, PAR4_END, \
    PAR5, PAR5_TYP, PAR5_FORMATFU, PAR5_FORMAT, PAR5_IS_GTK_WIDGET, PAR5_ARG6, PAR5_ARG7, PAR5_END, \
    PAR6, PAR6_TYP, PAR6_FORMATFU, PAR6_FORMAT, PAR6_IS_GTK_WIDGET, PAR6_ARG6, PAR6_ARG7, PAR6_END, \
    PAR1, PAR1_TYP, PAR1_FORMATFU, PAR1_FORMAT, PAR1_IS_GTK_WIDGET, PAR1_ARG6, PAR1_ARG7, PAR1_END, \
  PARS_END ) \
    typedef void(* gtksig_void_##PAR1##_##PAR2##_##PAR3##_##PAR4##_##PAR5##_##PAR6)(PAR1_TYP,PAR2_TYP,PAR3_TYP,PAR4_TYP,PAR5_TYP,PAR6_TYP); \
    void wrapper_void_##PAR1##_##PAR2##_##PAR3##_##PAR4##_##PAR5##_##PAR6(GtkBuilder* builder,char* COMMAND, char* arg1, char* arg2, char* arg3, char* arg4, char* arg5, char* arg6) { \
        if(DEBUG) fprintf(stderr,"GTKCALL 0-1-1-1-1-1-1 %2$s(%3$s, %4$s, %5$s, %6$s, %7$s, %8$s) (%1$s)\n",__func__,COMMAND,arg1,arg2,arg3,arg4,arg5,arg6); \
        void* gtk_vu=table_get_gtk_fu(COMMAND); \
        __PAR_TO_VALUE(PAR1_TYP,PAR1_IS_GTK_WIDGET,PAR1_FORMATFU,PAR1_FORMAT,PAR1_ARG7,arg1,value1) \
        __PAR_TO_VALUE(PAR2_TYP,PAR2_IS_GTK_WIDGET,PAR2_FORMATFU,PAR2_FORMAT,PAR2_ARG7,arg2,value2) \
        __PAR_TO_VALUE(PAR3_TYP,PAR3_IS_GTK_WIDGET,PAR3_FORMATFU,PAR3_FORMAT,PAR3_ARG7,arg3,value3) \
        __PAR_TO_VALUE(PAR4_TYP,PAR4_IS_GTK_WIDGET,PAR4_FORMATFU,PAR4_FORMAT,PAR4_ARG7,arg4,value4) \
        __PAR_TO_VALUE(PAR5_TYP,PAR5_IS_GTK_WIDGET,PAR5_FORMATFU,PAR5_FORMAT,PAR5_ARG7,arg5,value5) \
        __PAR_TO_VALUE(PAR6_TYP,PAR6_IS_GTK_WIDGET,PAR6_FORMATFU,PAR6_FORMAT,PAR6_ARG7,arg6,value6) \
        ((gtksig_void_##PAR1##_##PAR2##_##PAR3##_##PAR4##_##PAR5##_##PAR6)gtk_vu)(value1,value2,value3,value4,value5,value6); \
    }
#define SIGFU_CON_VOID_PAR1_PAR2_PAR3_PAR4_PAR5_PAR6(COMMAND,PAR1,PAR2,PAR3,PAR4,PAR5,PAR6) /*0-1-1-1-1-1-1*/ \
    table_add(#COMMAND,wrapper_void_##PAR1##_##PAR2##_##PAR3##_##PAR4##_##PAR5##_##PAR6,COMMAND);



